In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Week2 授業前課題3 行列積のスクラッチ

In [2]:
a_ndarray = np.array([[-1, 2, 3], 
                      [4, -5, 6], 
                      [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1],
                      [0, 2, -8],
                      [2, 9, -1]])

＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
### 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。
計算過程もマークダウンテキストを用いて説明してください。

#### A + B = 
#### [[(-1x0 + 2x0 + 3x2), (-1x2 + 2x2 + 3x9), (-1x1 + 2x-8 + 3x-1)],
####  [(4x0 + -5x0 + 6x2), (4x2 + -5x2 + 6x9), (4x1 + -5x-8 + 6x-1)],
####  [(7x0 + 8x0 + -9x2), (7x2 + 8x2 + -9x 9), (7x1 + 8x-8 + -9x-1)]]
 
#### =
 
#### [[(0 + 0 + 6), (-2 + 4 + 27), (-1 - 16 - 3)]
####  [(0 + 0 + 12), (8 - 10 + 54), (4 + 40 - 6)]
####  [(0 + 0 - 18), (14 + 16 - 81), (7 - 64 + 9)]]
  
####  =
  
####  [[6, 29, -20]
####   [12, 52, 38]
####   [-18, -51, -48]]


＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
### 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

■3種類の違い

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。

今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。

In [3]:
a_ndarray = np.array([[-1, 2, 3], 
                      [4, -5, 6], 
                      [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1],
                      [0, 2, -8],
                      [2, 9, -1]])

print(np.matmul(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [4]:
print(np.dot(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [5]:
print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
#### 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

##### ・行列Aの(0,0)の要素a0,0と行列Bの(0,0)の要素b0,0を掛け合わせる
##### ・行列Aの(0,1)の要素a0,1と行列Bの(1,0)の要素a1,0を掛け合わせる
##### ・行列Aの(0,2)の要素a0,2と行列Bの(2,0)の要素a2,0を掛け合わせる
##### ・それらの値を全て足し合わせる

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [6]:
a_ndarray = np.array([[-1, 2, 3], 
                      [4, -5, 6],
                      [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1],
                      [0, 2, -8],
                      [2, 9, -1]])

list_ndarray = []

for i in range(np.shape(a_ndarray)[1]):
    list_ndarray.append(a_ndarray[0, i] * b_ndarray[i, 0])
    
sum_ndarray = sum(list_ndarray)

print(sum_ndarray)

6


＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
### 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。
行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。
計算結果である 
3×3 の行列Cの各要素 cij は数式で表すと次のようになります。
for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス 
iやjを1増やすと、次の行や列に移ることができます。

In [7]:
a_ndarray = np.array([[-1, 2, 3], 
                      [4, -5, 6],
                      [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1],
                      [0, 2, -8],
                      [2, 9, -1]])


x_ndarray = np.array([[1, 2, 3],
                      [4, 5, 6]])
y_ndarray = np.array([[1],
                      [2],
                      [3]])

def multiplicate_matrix(ndarray1, ndarray2):
    row1 = np.shape(ndarray1)[0] # a_ndarrayの行数
    col1 = np.shape(ndarray1)[1] # a_ndarrayの列数
    row2 = np.shape(ndarray2)[0] # b_ndarrayの行数
    col2 = np.shape(ndarray2)[1] # b_ndarrayの列数
    list_num = [] # 各要素ごとの計算途中式を格納するリスト
    list_matrix = [] # 各要素ごとの計算結果を格納するリスト
    
    for i in range(row1):
        for j in range(col2):
            for k in range(col1):
                if k < col1-1:
                    list_num.append(ndarray1[i, k] * ndarray2[k, j])
                    
                else:
                    list_num.append(ndarray1[i, k] * ndarray2[k, j])
                    list_matrix.append(sum(list_num))
                    list_num.clear() # リストの要素を削除して初期化
                    
    multiplicate_matrix_ndarray = np.array(list_matrix).reshape(row1, col2) # list_matrixをndarrayにし、m×l型に変換
    
    return multiplicate_matrix_ndarray

ndarray1 = a_ndarray
ndarray2 = b_ndarray
multiplicated_matrix = multiplicate_matrix(ndarray1, ndarray2)

print(multiplicated_matrix)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
### 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。
if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [8]:
d_ndarray = np.array([[-1, 2, 3],
                    [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7],
                      [6, -5, 4]])

def multiplicate_matrix(ndarray1, ndarray2):
    row1 = np.shape(ndarray1)[0] # a_ndarrayの行数
    col1 = np.shape(ndarray1)[1] # a_ndarrayの列数
    row2 = np.shape(ndarray2)[0] # b_ndarrayの行数
    col2 = np.shape(ndarray2)[1] # b_ndarrayの列数
    list_num = [] # 各要素ごとの計算途中式を格納するリスト
    list_matrix = [] # 各要素ごとの計算結果を格納するリスト
    
    if col1 != row2:
        return ("エラー：行列Ａの列数( {} 列)と行列Ｂの行数( {} 行)が一致しないため行列積は定義できません".format(col1, row2))
        
    else:
        for i in range(row1):
            for j in range(col2):
                for k in range(col1):
                    if k < col1-1:
                        list_num.append(ndarray1[i, k] * ndarray2[k, j])

                    else:
                        list_num.append(ndarray1[i, k] * ndarray2[k, j])
                        list_matrix.append(sum(list_num))
                        list_num.clear() # リストの要素を削除して初期化

        multiplicate_matrix_ndarray = np.array(list_matrix).reshape(row1, col2) # list_matrixをndarrayにし、m×l型に変換

        return multiplicate_matrix_ndarray

ndarray1 = d_ndarray
ndarray2 = e_ndarray

multiplicated_matrix = multiplicate_matrix(ndarray1, ndarray2)

print(multiplicated_matrix)

エラー：行列Ａの列数( 3 列)と行列Ｂの行数( 2 行)が一致しないため行列積は定義できません


＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
### 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。
np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [9]:
d_ndarray = np.array([[-1, 2, 3],
                    [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7],
                      [6, -5, 4]])

d_ndarray = d_ndarray.T # d_ndarrayを転置

ndarray1 = d_ndarray
ndarray2 = e_ndarray

multiplicated_matrix = multiplicate_matrix(ndarray1, ndarray2)

print(multiplicated_matrix)

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
